### ISSUE TITLE
File-based cache is not updated

### ISSUE THREAD

**Issue by fra967** [dadi/cache#16]
Cache 1.5.1, with Web 1.8.0 or API 1.16.3, in both cases configured to use file-based caching
`caching.directory.enabled: true`
with a low ttl (300)

With cluster: true

Files are saved in the cache directory either as root user (the node process is running as root) or as ubuntu user.

New requests after 300 seconds still use the local cached file

Possible related to https://github.com/dadi/api/issues/253

**Comment by fra967** [comment]
this is blocking us from using cluster mode for web & api, which would be quite useful in production environments

**Comment by jimlambie** [comment]
@fra967 Can you give any more details about how the service is running? Is it running as root or ubuntu?

**Comment by fra967** [comment]
Cannot reproduce any more with 1.5.3
