### ISSUE TITLE
Cache error when saving local file

### ISSUE THREAD

**Issue by fra967** [dadi/cache#19]
cache 1.5.3, used by cdn 1.12.1 with 
`caching.directory.enabled: true`

whenever a copy of an image is saved in the local cache directory, the following error is logged

```
Error: The specified key does not exist
    at fs.stat (/data/cdn/node_modules/@dadi/cache/lib/file.js:59:23)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

https://github.com/dadi/cache/blob/master/lib/file.js#L59

Functionality is not impacted, but it bloats the error log

**Comment by jimlambie** [comment]
I remember this being removed at some point. Looks like it'll be removed again... thanks @fra967

**Comment by jimlambie** [comment]
This is resolved in CDN - it's right for Cache to reject with an error of this nature, and up to the consuming application to report it as necessary. Closing.
